Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
X, y = make_blobs(n_samples=1000, centers=2, n_features=2,cluster_std=3,random_state=2021)
y[y==0]=-1
data = pd.DataFrame(X)
data['y'] = y
sns.pairplot(data,hue='y',palette='tab10', corner=True)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Input [0;32mIn [2][0m, in [0;36m<cell line: 3>[0;34m()[0m
[1;32m      1[0m X, y [38;5;241m=[39m make_blobs(n_samples[38;5;241m=[39m[38;5;241m1000[39m, centers[38;5;241m=[39m[38;5;241m2[39m, n_features[38;5;241m=[39m[38;5;241m2[39m,cluster_std[38;5;241m=[39m[38;5;241m3[39m,random_state[38;5;241m=[39m[38;5;241m2021[39m)
[1;32m      2[0m y[y[38;5;241m==[39m[38;5;241m0[39m][38;5;241m=[39m[38;5;241m-[39m[38;5;241m1[39m
[0;32m----> 3[0m data [38;5;241m=[39m [43mpd[49m[38;5;241m.[39mDataFrame(X)
[1;32m      4[0m data[[38;5;124m'[39m[38;5;124my[39m[38;5;124m'[39m] [38;5;241m=[39m y
[1;32m      5[0m sns[38;5;241m.[39mpairplot(data,hue[38;5;241m=[39m[38;5;124m'[39m[38;5;124my[39m[38;5;124m'[39m,palette[38;5;241m=[39m[38;5;124m'[39m[38;5;124mtab10[39m[38;5;124m'[39m, corner[38;5;241m=[39m[38;5;28;01mTrue[39;00m)

[0;31mNameError[0m: name 'pd' is not defined
NameError: name 'pd' is not defined

